### ISSUE TITLE
Add Documentation in README.md

### ISSUE THREAD

**Issue by juaan** [anthonyjuan/hacktivoverflow-react#1]
Can anyone add Documentation for API List ? you can see it in /server/routes/*

**Comment by NataliaZhydeikina** [comment]
I try this

**Comment by NataliaZhydeikina** [comment]
If I use ApiDoc.js,  if you don't mind.

**Comment by aiyankovil** [comment]
what api list we should add
@anthonyjuan 
facebook twitter instagram...
